### ISSUE TITLE
选择激活claude/chatgpt后提示激活成功，但是无其它响应

### ISSUE THREAD

**Issue by Payne-Wang** [Kylsky/pandora-helper-with-linux-do-oauth#4]
大佬好，

  这个应用部署之后，选择激活，提示激活成功，但是无法跳转到fuclaude，这个正常吗？谢谢
  

 
![image](https://github.com/user-attachments/assets/914366f2-c05d-4d82-8bd0-ba3b142ead5d)
![image](https://github.com/user-attachments/assets/28c080fc-ed26-4661-abc5-0de37d3d53f7)

我的配置
```
version: '3'
services:
  pandora-helper:
    image: kylsky/pandora_helper
    volumes:
      - db-data:/app/db
    environment:
      CLIENT_ID: "QVg4pK0UXXXXXXXXXXXXXXX"                                   # 1.你的linux-do oauth client
      CLIENT_SECRET: "7gOGdAXXXXXXXXXXXXXXX" 
      REDIRECT_URI: "http://我的IP:8189"                                # 3.必填，你的应用地址
      OAIFREE_PROXY: "https://new.oaifree.com"        # 4.默认oaifree，你可以填写你的代理地址
      FUCLAUDE_PROXY: "https://demo.fuclaude.com"     # 5.默认fuclaude，你可以填写你的fuclaude地址
      TZ: "Asia/Shanghai"
      ADMIN_NAME: "Admin"                             # 6.管理员用户名，建议填写你在linux-do的用户名，默认密码是123456

    ports:
      - "8189:8181"                                   # 7.如需修改端口，请修改第一个8181为你需要访问的服务器端口
    restart: always

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/pandorahelper/db                # 8.指定宿主机的数据库挂载目录，必须使用绝对路径
```
